### ISSUE TITLE
These examples not working for Tizen OS

### ISSUE THREAD

**Issue by rcmahapatra** [jamesplease/lrud#110]
The examples provided is not working for tizen os.

**Comment by jamesplease** [comment]
See #67. This lib isn't currently tested on Tizen and is unlikely to ever be tested on Tizen, I'm afraid!

**Comment by alexander-gusev-dev** [comment]
lrud v0.0.23 works fine on Tizen TV across all models starting 2018
Tizen 2017 has works width lrud 0.0.18
