### ISSUE TITLE
Navigation issue when adding elements dynamically

### ISSUE THREAD

**Issue by clementhoubrecrunchy** [jamesplease/lrud#114]
Hi,

I would like to raise an issue I got in my project when using **lrud**:

When we add elements into a existing list at a specific position (but not the end), when we want to navigate with the keyboard, the navigation will not work correctly.

Here is a demo that shows what is the problem: https://codesandbox.io/p/sandbox/focusnode-with-dynamic-list-with-bug-forked-p2vkhm?file=%2Fsrc%2FList.tsx%3A1%2C1
- Launch the demo
- You can navigate with "**left**" / "**right**" keys without any problems in the list.
- Press "**enter**" key: It will add an element at a random position in the list.
- Try to navigate again in the list: we can observe issue in the navigation.

What can we do to solve the problem ? Or a fix is necessary ?

Thanks in advance!

**Comment by jamesplease** [comment]
Closing, sorry won’t fix this.
