### ISSUE TITLE
Can we use this library for production application ?

### ISSUE THREAD

**Issue by asishap007** [jamesplease/lrud#34]
Hi 
We are planning to create a TV application. For navigation purpose can we use this library for production purpose ?
Is there any performance bench mark for this library ?

**Comment by jamesplease** [comment]
Aside from the fact that there are zero tests (#6 ), the types may only be 98% accurate (#17), and that there are a few known issues (#31), it should be prod-ready.

For most typical TV interfaces, perf won't be a problem for _any_ LRUD solution, including this lib. If you have long/infinite lists, you'll want to virtualize the DOM, and this lib may or may not play well with virtualization.
