### ISSUE TITLE
Navigation does not work on tizen 3

### ISSUE THREAD

**Issue by marinbonibon** [jamesplease/lrud#67]
Hello, we are faced with the problem that navigation does not work on tizen 3. Could you, please, give some advice on how to fix this?

**Comment by jamesplease** [comment]
Hey there! What device are you using? Are you using an input device that’s either a keyboard or TV remote mapped to keyboard directional arrows?

**Comment by marinbonibon** [comment]
We tested on an emulator using both a keyboard and a TV remote, as well as on a real device using a TV remote. Started from tizen 4 everything works fine.

**Comment by jamesplease** [comment]
Do you have a dev tools environment available? Are you getting any errors?

My guess is that I'm compiling down to a particular version of ECMAScript that Tizen 3 does not support (the config [builds for relatively new browsers](https://github.com/jamesplease/lrud/blob/961795f2b3ec4061a82ecd8e1143e7ac0ebf4190/babel.config.js#L9-L13)). For example, perhaps there are arrow functions in the compiled source and Tizen 3 does not support those.

If the above is true, then one way you could get around it would be to add your own build step that ensures that nothing is included that Tizen 3 does not support. Then, run that on your deps.

**Comment by marinbonibon** [comment]
Yes, we have dev tools environment available and there are no errors.

**Comment by jamesplease** [comment]
I think that's about the extent of my ability to help out with this issue, I'm afraid. I've never used Tizen/don't own any Tizen devices, and it's unlikely that I'll ever officially support any version of Tizen in this lib.

I'd definitely double check to make sure that your entire app (including all dependencies) compiles down to Tizen 3-compatible ES!

If you determine that any specific code in this lib is causing the issue, feel free to open a PR and I'll merge it in.

Best of luck!
