### ISSUE TITLE
compile target feels too modern

### ISSUE THREAD

**Issue by JohnPaulHarold** [jamesplease/lrud#69]
I just tried importing this library to a React project but encountered errors about `import not supported` and such like. 

Looking at the code produced after a build, it's all using ES6 modules, rather than CJS. I think it's also using latest and greatest ES6 features which might not have support. Certainly not across set top boxes which can vary in what JS they support.

**Comment by jamesplease** [comment]
Popular out-of-the-box bundlers like CRA and Next should be able to import this and then transpile it down to whatever your ES requirements are. Were you running into issues with one of those?

I'm afraid I won't have time to make any changes to the distribution format.

**Comment by JohnPaulHarold** [comment]
sadly for me, this project I am working on is neither CRA or Next: it's got a webpack configuration, targeting ES5/ES2015, but for some reason your file is refusing to transpile. I ran a check on my repo and this lib is one of about 4 that isn't ES5, everyone else isn't requiring as much. I used this lib to determine it's ES5-ness, https://github.com/obahareth/are-you-es5#readme. It also generates a regex you can use in your webpack config.

I will dig in some more on my side and try and work it out. I've used your lib before, but with a CRA ejected app, so I guess I'll dig in and find out what this current project is doing wrong, or missing, with `node_modules` transpilation.

**Comment by jamesplease** [comment]
Best of luck! And sorry for the trouble.

**Comment by jamesplease** [comment]
Update: I did just notice #50 which I think would solve your issue. It's not currently on my immediate roadmap to investigate but if I ever get around to it I'll be sure to ping ya!
