### ISSUE TITLE
[BUG] Changing one of `dynamicNodeProps` of a parent node, overwrite children nodes `disabled` and `isExiting` recursively without preserving it on normal state

### ISSUE THREAD

**Issue by LBRDan** [jamesplease/lrud#71]
Codesandbox reproduction: [Here](https://codesandbox.io/s/please-parent-dynamicprops-isdisabled-bug-pm0ni?file=/src/App.js)

Everything that triggers a change in node inside `updateNode` (and every props in deps array in [HERE](https://github.com/jamesplease/lrud/blob/main/src/focus-node.tsx#L383-L409) / [HERE](https://github.com/jamesplease/lrud/blob/961795f2b3ec4061a82ecd8e1143e7ac0ebf4190/src/focus-store.ts#L31-L40)) eventually spreads recursively parent `disabled` and `isExiting` to every children, (without respecting single child configuration on neutral condition (disabled = `false` and isExiting = `false`) (Code ref [HERE](https://github.com/jamesplease/lrud/blob/961795f2b3ec4061a82ecd8e1143e7ac0ebf4190/src/focus-store.ts#L335-L336))

The expected behavior is that changing something on parent should ideally update children only if necessary (ex. changes to specifically `disabled` and `isExiting`). On behalf of these parameters, it should keep single child nodes configuration when these flags are set back to "neutral" (false), restoring something like the current node prop singularly

**Comment by jamesplease** [comment]
Will take a look soon. Thanks for the issue, and especially for taking the time to create the CodeSandbox and to be so thorough in this bug report.

**Comment by jamesplease** [comment]
Will try to get to this one next week ✌️

**Comment by jamesplease** [comment]
Fix published as `0.0.23`
