### ISSUE TITLE
[Incomplete Types] Default/Custom `elementType` does not extend/affect `FocusNode` props, triggering errors

### ISSUE THREAD

**Issue by LBRDan** [jamesplease/lrud#72]
Using this library with Typescript, taking advantage of the wrapper element inside the `FocusNode`s currently triggers type errors when using `HTMLElement` props
Ex (As per docs, using motion.div as custom element):
```ts
import motion from 'framer-motion';

function MyComponent(props) {
// ...
	return <FocusNode  focusId="TEST" elementType={motion.div} onAnimationStart={() => {}} />
}
// ...
```
`onAnimationStart` prop triggers an error or is not typed as no type inference is applied to elementType

I tried several solutions, but none seems to work appropriately (including Inferring generics and distributing them to get `React.ComponentProps<T>`)

Do you have something in mind about this? I see that this library is entirely in Typescript but all the samples are in plain JS
Maybe the way `framer-motion` or even `styled-components` is typed could help to achieve this
Any suggestions?

**Comment by jamesplease** [comment]
Thanks for opening the issue! The fastest way to get this resolved would be opening a PR that fixes it. Unfortunately I can't commit to a timeline on when I could get this sorted out myself.

**Comment by jamesplease** [comment]
Closing, sorry, I won’t be able to fix this.
