### ISSUE TITLE
defaultFocusChild triggers wasteful rerenders when passed as a callback

### ISSUE THREAD

**Issue by LBRDan** [jamesplease/lrud#77]
Similar to #71 
Unlike other external callbacks ( ex.`onKey`), the dual reactive nature on `defaultFocusChild` (as a part of the `dynamicNodeProps` listed [here](https://github.com/jamesplease/lrud/blob/main/src/focus-store.ts#L31)) may trigger a rerender when passed as a non memoized callback, when the parent component gets rerendered

If the parent component have a subscription using  to the component where `defaultFocusChild` is passed, it starts a rerender loop (parent watching child change, then a new callback is passed, then change triggered in the node and so on...)

Technically the node it's changing and its update should trigger the hook to trigger, but `defaultFocusChild` maybe is intended to be a "passive" prop, and should maybe be treated as a ref more than a pure reactive prop

CodeSandbox [Here](https://codesandbox.io/s/please-parent-rerender-loop-mfy75) - (To trigger this, uncomment the line 36)

**Comment by jamesplease** [comment]
Thanks for opening this issue!

Honestly, I’m not sure when I’ll have time to look into this but if you’re able to PR a fix I can try to get it released.

**Comment by LBRDan** [comment]
Believe me, I could if I were able to
As you said in previous issues, This library is a bit tough on the computational aspect and I'll keep on opening issues as long as I found it (if that's still ok for you, ofc)

About this particular issue, it seems a lot more on the architectural/conceptual side, more than about the implementation itself, and if you can express a preference I can try to figure out a fix for you

In my opinion, keeping `defaultFocusChild` inside the category of "props i need to react to as soon an they do" is not completely right
Sure, you must keep its reference as fresh as possible across the nodes inside the focusStore, but triggering a full update on a node property that cannot change the current focus state seems off track

What is your opinion about this?

**Comment by jamesplease** [comment]
Will prioritize fixing this one next...hopefully next week! The CodeSandboxes you are posting are incredible...thank you so much!
