### ISSUE TITLE
Consider: bubbling select event when clicking with a pointer device

### ISSUE THREAD

**Issue by jamesplease** [jamesplease/lrud#82]
Pointer device support in this lib is, admittedly, a bit less solid than keyboard support. Atm it looks like the `onSelected` event doesn't bubble when clicking on a FocusNode.

Todo:

- [x] Verify that this is true
- [x] Decide if it should bubble or not in this situation
- [ ] Make any necessary changes based on the above

**Comment by jamesplease** [comment]
> It's true ([CodeSandbox](https://codesandbox.io/s/please-onclick-mouse-bubble-onselect-u2ri5?file=/src/App.js)), as it is triggered inside the FocusNode itself via an bound onClick function handler onto the elementType ([Here](https://github.com/jamesplease/lrud/blob/main/src/focus-node.tsx#L506))

Thanks for looking into this!

> To make this work, it should rely upon `bubbleKey(store, 'select');` passing some other params maybe to identify the source of event(?) (maybe could be useful to receive this information inside the callback)

👍 Re: source, see #66 


> In my opinion, if the `onSelected` gets triggered I assume that so happens despite of the event that triggers the selection. Otherwise, a new specialized "onClicked" callback should be added.

Hmmm, I'm not sure I follow. Would you mind rephrasing this sentence?

> Currently this library mimics DOM event's behavior (Thanks @giankd for the demo [HERE](https://codesandbox.io/s/laughing-tdd-wy53f?file=/src/App.tsx)) so it appears to me that every event, despite of its source bubbles the dom tree up to the document

👍

**Comment by LBRDan** [comment]
> > In my opinion, if the `onSelected` gets triggered I assume that so happens despite of the event that triggers the selection. Otherwise, a new specialized "onClicked" callback should be added.
> 
> Hmmm, I'm not sure I follow. Would you mind rephrasing this sentence?
> 

Sure! 
When (as a library user) i implement my custom `onSelected` on a specific node i expect that it will be called when a FocusNode, or one of its children gets selected.
Now, assume that i read about the pointerEvents prop inside the FocusRoot's docs.
"Cool stuff! I'll just pop this boolean inside the focus root and i'm set!"
In my DOM composition (as per @giankd sandbox) this may lead to trigger only the specific node that implements `onSelected` to be called, without bubbling, making the lib behavior different from using pointer event or key events


I hope I've made myself clear now
I'm sorry, my english is not that good 😞

**Comment by jamesplease** [comment]
Super clear. That does make sense :+1: Thank you for elaborating!

**Comment by jamesplease** [comment]
Update: the reason that I manually did this rn is that the current `bubbleKey` bases it off of what's in focus. This works for remote input, because when you press `Enter` the source is always the leaf focused node.

However, you can click anywhere on the screen, so the source could be different.

Supporting this will require:

1. a function to generate an arbitrary hierarchy from a focus node
2. being able to optionally pass the hierarchy into `bubbleKey`, to bubble events up an arbitrary hierarchy
3. calling this in `onClick`
