### ISSUE TITLE
New architecture

### ISSUE THREAD

**Issue by jamesplease** [jamesplease/lrud#98]
This issue captures some discussion in other threads.

- three kinds of components: `FocusScreen`, `FocusGroup`, `FocusNode`.
- current nav algo involves nested `FocusGroup` and `FocusNode`.
- new algo introduced: `SpatialScreen`. Only `FocusNode`s are permitted as children.

I think this would solve all of the known issues in the lib that I can think of rn, at the expense of a slightly more verbose API.

---

- `FocusScreen`: solves exit/intro animation issues
- `FocusGroup`: solves the problem described in this issue
- `SpatialFocusGroup`: solves the long-standing issue of needing spatial navigation, and avoids a problem where somebody is annoyed by needing to manage nested FocusGroups and FocusNodes.

- At the same time, I should add the focus source (#66 )
- rewrite how prop updates occur and how they're propagated down to children (#71 , #100 )
- Also -- add `enforce-state-structure` tests after the refactor
- Consider `defaultFocusChild` at mount ( #70 )

Ref: #92, #68, #63, #62, #93 , #70

**Comment by LBRDan** [comment]
`SpatialFocusGroup` looks amazing as the first high-level feature!
Maybe some of these problem could be natively resolved with it (please correct me if I'm wrong):
- Having a list and remembering the `latestFocusedChildIndex` without external `defaultFocusIndex` management
- Swapping dynamic spawning FocusNode  (really no one maintaining any spatial navigation lib solves this real world problem without throwing `key` prop index based in the mud) (eg. Say inside a Search Area, There is a list changing its children order as the user types the search term)
- Having a list with "wrap around scroll" only in one direction (eg. horizontal list rotating only right from the nth-child to the first but not backward)

**Comment by jamesplease** [comment]
> Having a list and remembering the latestFocusedChildIndex without external defaultFocusIndex management

👍

> Swapping dynamic spawning FocusNode

Hmmm...I don't follow this one.

> Having a list with "wrap around scroll" only in one direction

Implementing this should be about the same level of effort in both systems.

---

imo spatial navigation is best used in a few key areas where the current nav algo is particularly tedious to use, but I know others feel differently 😁

One great spot for spatial nav, imo, is in a grid-like arrangement where one of the rows of items is dynamic size. Very tedious to do in the current setup; trivial with spatial nav.

**Comment by jamesplease** [comment]
Just a note: store propagated props (like `isExiting`, `disabled`) down through context.
